### ISSUE TITLE
Generated variables are missing an argument

### ISSUE THREAD

**Issue by tbhosman** [project-march/slave-tools#3]
Generates this:
`{0x01, DTYPE_UNSIGNED32, 32, ATYPE_RO, acName7000_01, &Rb.Outputs.testToSlave}`

Should be this:
`{0x01, DTYPE_UNSIGNED32, 32, ATYPE_RO, acName7000_01, 0, &Rb.Outputs.testToSlave}`

**Comment by Ortix92** [comment]
@Etruscian You had 1 job
