### ISSUE TITLE
objectlist.h has invalid PDO defines

### ISSUE THREAD

**Issue by tbhosman** [project-march/slave-tools#8]
Following lines should be removed from the file generation:

```
 #define UARTIn In._PDO_In.UARTInput
 #define FloatTest In._PDO_In.CokeFloat 
 #define LEDState Out._PDO_Out.someLED
```

In addition, these defines should be added for the variables that are used in the generation. E.g. adding "distance" should result in:

` #define distance In._PDO_In.distance 
`

**Comment by Etruscian** [comment]
commit 76d5 should fix this issue, please confirm

**Comment by tbhosman** [comment]
Confirmed!

**Comment by tbhosman** [comment]
De-confirm :p In and Out are mixed up still, and semicolon should be removed :)

Now:
`#define uint8_test Out._PDO_Out.uint8_test;`

Should be:
'#define uint8_test In._PDO_In.uint8_test;'
